version: '3'

services:
  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app/mande"
    depends_on:
      - postgres
    command:
      - sh -c 'npm start'

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
