version: '3'

services:
  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app/mande"
      - "/app/mande/node_modules"

    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    volumes:
      - ./dbschema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres